mule:
  error:
    category:
      technical: "TECHNICAL"
      business: "BUSINESS"
    severity:
      major: "MAJOR"
      critical: "CRITICAL"
      minor: "MINOR"
    type:
      "400": 
        code: "400"    
        description: "Bad Request."
      "404": 
        code: "404"    
        description: "The URI requested is invalid or the resource requested does not exists."
      "405": 
        code: "405"    
        description: "A request was made of a resource using a request method not supported by that resource."
      "406": 
        code: "406"    
        description: "The server cannot respond with the accept-header specified in the request."
      "415": 
        code: "415"    
        description: "The request entity has a media type which the server or resource does not support."
      "401": 
        code: "401"    
        description: "Unauthorized."
      "500": 
        code: "500"    
        description: "Internal Server Error."